<?php

$config = array(
             	


				'multimedia' => array(array(
                                	'field'=>'nMultTipoID',
                                	'label'=>'NMultTipoID',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nMultCategID',
                                	'label'=>'NMultCategID',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultLinkMiniatura',
                                	'label'=>'CMultLinkMiniatura',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultLink',
                                	'label'=>'CMultLink',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultTitulo',
                                	'label'=>'CMultTitulo',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultDescripcion',
                                	'label'=>'CMultDescripcion',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultFechaRegistro',
                                	'label'=>'CMultFechaRegistro',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultFechaInicial',
                                	'label'=>'CMultFechaInicial',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nParID',
                                	'label'=>'NParID',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultEstado',
                                	'label'=>'CMultEstado',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cMultNumVisitas',
                                	'label'=>'CMultNumVisitas',
                                	'rules'=>'required|trim|xss_clean'
                                ))
			   
			   
				,

				'eventos' => array(array(
                                	'field'=>'cEveLatitud',
                                	'label'=>'CEveLatitud',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveLongitud',
                                	'label'=>'CEveLongitud',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveTitulo',
                                	'label'=>'Titulo',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveDescripcion',
                                	'label'=>'Descripcion',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveLinkFoto',
                                	'label'=>'LinkFoto',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveLinkFacebook',
                                	'label'=>'LinkFacebook',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveDireccion',
                                	'label'=>'Direccion',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'dEveStartTime',
                                	'label'=>'Fecha Empiezo',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'dEveEndTime',
                                	'label'=>'Fecha Termino',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nUbiDepartamento',
                                	'label'=>'Departamento',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'nUbiProvincia',
                                	'label'=>'Provincia',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'nUbiDistrito',
                                	'label'=>'Distrito',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'dEveFechaRegistro',
                                	'label'=>'FechaRegistro',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'cEveEstado',
                                	'label'=>'Estado',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nEveCosto',
                                	'label'=>'Costo',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nUsuario',
                                	'label'=>'Usuario',
                                	'rules'=>'required|trim|xss_clean'
                                ))
			   );
			   
?>